version: '3'

services:
  db:
    container_name: db
    image: postgres
  backend:
    container_name: django_api_vue
    build: ./backend
    command: /start.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db